---
# By default do image conversion in the global working_dir
convert_image_working_dir: "{{ working_dir }}"
convert_image_template: convert_image.sh.j2

# Do a yum update when converting overcloud to undercloud
convert_image_update: true

# List of packages that should be removed from the overcloud image
convert_image_remove_pkgs:
  - cloud-init
  - python-django-horizon
  - openstack-dashboard

# List of packages that should be installed to convert overcloud to undercloud
# <wes> notes this was a list, but is now a string
# still should work w/ https://opendev.org/openstack/tripleo-quickstart/src/branch/master/roles/convert-image/templates/convert_image.sh.j2#L24
convert_image_install_pkgs: "{{ 'python3-tripleoclient' if ansible_distribution_major_version|int >= 8 else 'python-tripleoclient' }}"

convert_image_tempest_plugins: []
convert_image_host_memory: 2048
guest_partition: /dev/sda
