##################################################
# FEATURESET052 - TRIPLEO STANDALONE
##################################################

non_root_user_setup: true
ovb_setup_connectivity: false
package_installs: true
vxlan_networking: false
toci_vxlan_networking: false
enable_vbmc: false
deploy_supplemental_node: false
undercloud_setup: true

# role / scenario definition
# deployment role
standalone_role: Standalone.yaml

# custom env files
standalone_custom_env_files:
  - /usr/share/openstack-tripleo-heat-templates/environments/low-memory-usage.yaml

# validation

# If `run_tempest` is `true`, run tempests tests, otherwise do not
# run them.
test_ping: false
# Running only smoke tests and a few scenarios
test_white_regex: '\[.*\bsmoke\b.*\]'
# NOTE(aschultz): containers assume RC at the moment
tempest_undercloud: true
tempest_overcloud: false
tempest_workers: 2
tempest_os_cloud: standalone

# This is only if we want to execute the tests on the skiplist
# TODO(arxcruz): This needs to be modified when we have the tempest skiplist
# tool
skip_test_file: "{{ playbook_dir | dirname }}/vars/tempest_skip_{{ release | default('master') }}.yml"
skip_list_tests: "{{ lookup('file', skip_test_file) | from_yaml }}"

tempest_tests_skipped: "{{ skip_list_tests.known_failures | json_query('[?undercloud != `true`].test') }}"
tempest_default_whitelist:
  - 'tempest.scenario.test_minimum_basic.TestMinimumBasicScenario'
  - 'tempest.scenario.test_network_basic_ops.TestNetworkBasicOps'
  - 'tempest.scenario.test_volume_boot_pattern.TestVolumeBootPattern'

tempest_whitelist: >-
  {% if tempest_run_skipped | default(false) | bool -%}
  {{ tempest_tests_skipped }}
  {%- else -%}
  {{ tempest_default_whitelist }}
  {%- endif -%}

# Settings for os_tempest
run_tempest: >-
  {% if release not in ['pike', 'queens', 'rocky', 'stein'] -%}
  false
  {%- else -%}
  true
  {%- endif -%}

use_os_tempest: >-
  {% if release not in ['pike', 'queens', 'rocky', 'stein'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}

tempest_periodic_regex:
  - 'smoke'

tempest_test_whitelist: >-
  {% if (('periodic' in zuul.pipeline and not job.force_non_periodic|default(false)|bool) or (job.force_periodic|default(false)|bool)) and not tempest_run_skipped | default(false) | bool -%}
  {{ tempest_periodic_regex }}
  {%- else -%}
  {{ tempest_whitelist }}
  {%- endif -%}

tempest_run_concurrency: 2

standalone_container_cli: >-
  {% if release in ['rocky'] -%}
  docker
  {%- else -%}
  podman
  {%- endif -%}
