####################################
# FEATURESET047 - UNDERCLOUD UPGRADE
# Based on featureset003
####################################

undercloud_generate_service_certificate: false
ssl_overcloud: false
undercloud_check_idempotency: true
undercloud_check_sanity: true

containerized_undercloud: >-
  {% if release in ['newton','ocata','pike','queens'] -%}
  false
  {%- else -%}
  true
  {%- endif -%}
containerized_overcloud: >-
  {% if release in ['newton', 'ocata', 'pike'] -%}
  false
  {%- else -%}
  true
  {%- endif -%}
containerized_undercloud_upgrade: >-
  {% if release in ['newton', 'ocata', 'pike', 'queens'] -%}
  false
  {%- else -%}
  true
  {%- endif -%}
containerized_overcloud_upgrade: >-
  {% if release in ['newton', 'ocata', 'pike'] -%}
  false
  {%- else -%}
  true
  {%- endif -%}

undercloud_cloud_domain: "localdomain"
undercloud_undercloud_hostname: "undercloud.{{ undercloud_cloud_domain }}"

# Tripleo-upgrade specific parameters
undercloud_upgrade: true
overcloud_deploy_script: "{{ working_dir }}/overcloud_deploy.sh"
tripleo_ci: true
use_oooq: true

# Deactivate validations as there is no overcloud
test_ping: false
run_tempest: false
