####################################################################################################
# FEATURESET062 - TRIPLEO STANDALONE FOR OCTAVIA - TRACKS SCENARIO 10
# This is a modified version of featureset 052 (standalone) so changes made
# to that featureset should be examined to see if they are relevant here.
####################################################################################################

non_root_user_setup: true
ovb_setup_connectivity: false
package_installs: true
vxlan_networking: false
toci_vxlan_networking: false
enable_vbmc: false
deploy_supplemental_node: false
undercloud_setup: true

# role / scenario definition
# deployment role
standalone_role: Standalone.yaml

# custom env files
standalone_custom_env_files:
  - /usr/share/openstack-tripleo-heat-templates/environments/low-memory-usage.yaml

standalone_container_cli: >-
  {% if release in ['rocky'] -%}
  docker
  {%- else -%}
  podman
  {%- endif -%}
# We need to selectively re-enable the globally blacklisted octavia tempest
# plugin.
tempest_private_net_seg_id: ''

test_ping: false

# os_tempest config

use_os_tempest: true

tempest_test_whitelist:
  - 'octavia_tempest_plugin.tests.scenario'
tempest_services:
  - octavia
  - neutron
tempest_run_concurrency: 2
download_amphora: true
amphora_url: 'https://images.rdoproject.org/octavia/{{ release }}/amphora-x64-haproxy-centos.qcow2'

tempestconf_override:
  load_balancer.test_with_ipv6: false

tempestconf_train_override:
  load_balancer.member_role: '"Member"'
  load_balancer.test_with_ipv6: false

tempest_tempestconf_profile_overrides: "{{ tempestconf_train_override if release in ['train'] else tempestconf_override }}"
tempest_os_cloud: standalone
