####################################################################################################
# FEATURESET062 - TRIPLEO STANDALONE FOR OCTAVIA - TRACKS SCENARIO 10
# This is a modified version of featureset 052 (standalone) so changes made
# to that featureset should be examined to see if they are relevant here.
####################################################################################################

non_root_user_setup: true
ovb_setup_connectivity: false
package_installs: true
vxlan_networking: false
toci_vxlan_networking: false
enable_vbmc: false
deploy_supplemental_node: false
undercloud_setup: true

# role / scenario definition
# deployment role
standalone_role: Standalone.yaml

# custom env files
standalone_custom_env_files:
  - /usr/share/openstack-tripleo-heat-templates/environments/low-memory-usage.yaml

# We need to selectively re-enable the globally blacklisted octavia tempest
# plugin.
skip_test_file: "{{ playbook_dir | dirname }}/vars/tempest_skip_{{ release | default('master') }}.yml"
skip_list_tests: "{{ lookup('file', skip_test_file) | from_yaml }}"
skip_file_src: ''
tempest_black: "{{ skip_list_tests.known_failures | json_query('[?test != `octavia_tempest_plugin`].test') }}"
test_black_regex: "{{ tempest_black }}"

# If `run_tempest` is `true`, run tempests tests, otherwise do not
# run them.
test_ping: false
run_tempest: true
tempest_undercloud: true
download_amphora: true
tempest_overcloud: false
tempest_workers: 2
test_white_regex: ''
tempest_whitelist:
  - 'octavia_tempest_plugin.tests.scenario.v2.test_load_balancer.LoadBalancerScenarioTest'
tempest_plugins:
  - python-octavia-tests-tempest
tempest_extra_config:
  load_balancer.member_role: '"Member"'
  load_balancer.test_with_ipv6: false
tempest_os_cloud: standalone

standalone_container_cli: >-
  {% if release in ['rocky'] -%}
  docker
  {%- else -%}
  podman
  {%- endif -%}
