---
add_repos:
  - type: generic
    reponame: centos8stream-base
    filename: "centos8stream-base-dependency.repo"
    priority: 1
    baseurl: "http://mirror.den01.meanservers.net/centos/8-stream/BaseOS/x86_64/os/"
    update_container: false
  - type: generic
    reponame: centos8stream-appstreams
    filename: "centos8stream-appstreams-dependency.repo"
    priority: 1
    baseurl: "http://mirror.den01.meanservers.net/centos/8-stream/AppStream/x86_64/os/"
    update_container: false
  - type: generic
    reponame: centos8stream-powertools
    filename: "centos8stream-powertools-dependency.repo"
    priority: 1
    baseurl: "http://mirror.den01.meanservers.net/centos/8-stream/PowerTools/x86_64/os/"
    update_container: false
  - type: generic
    reponame: centos8stream-highavailability
    filename: "centos8stream-highavailability-dependency.repo"
    priority: 1
    baseurl: "http://mirror.den01.meanservers.net/centos/8-stream/HighAvailability/x86_64/os/"
    update_container: false
  - type: generic
    reponame: centos8stream-extras
    filename: "centos8stream-extras-dependency.repo"
    priority: 1
    baseurl: "http://mirror.den01.meanservers.net/centos/8-stream/extras/x86_64/os/"
    update_container: false
  - type: generic
    reponame: centos8stream-cr
    filename: "centos8stream-cr-dependency.repo"
    priority: 1
    baseurl: "http://mirror.den01.meanservers.net/centos/8-stream/cr/x86_64/os/"
    update_container: false
dependency_override_repos:
  - quickstart-centos-base
  - quickstart-centos-appstreams
  - quickstart-centos-powertools
  - quickstart-centos-highavailability
  - quickstart-centos-extras
dep_repo_cmd_after: |
  {% if dependency_override_repos is defined %}
  {% for item in dependency_override_repos %}
  sudo sed -i -e "s|enabled=1|enabled=0|g" /etc/yum.repos.d/{{ item }}.repo;
  {% endfor %}
  sudo dnf clean all;
  sudo dnf update -y;
  {% endif %}
