overcloud_nodes:
  - name: control_0
    flavor: control
    default_name: overcloud-controller-0
    hostnamemap_override: "{{ hostvars[groups['overcloud'][0]].ansible_hostname }}"
  - name: control_1
    flavor: control
    default_name: overcloud-two-controller-0
    hostnamemap_override: "{{ hostvars[groups['overcloud'][1]].ansible_hostname }}"

node_count: 2

deployed_server_overcloud_roles:
  - name: Controller
    hosts: "$(sed -n 1,1p /etc/nodepool/sub_nodes_private)"

topology_map:
  Compute:
    scale: 0
